# Generated by Django 4.2.2 on 2023-06-21 05:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_create_default_beer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('flow_volume', models.FloatField()),
                ('is_open', models.BooleanField(default=False)),
                ('openings', models.IntegerField(default=0)),
                ('total_open_time', models.TimeField(default=datetime.time(0, 0))),
                ('open_time', models.DateTimeField(null=True)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.beer')),
            ],
        ),
    ]
